name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        find . -name "*.c" -print0 | while IFS= read -r -d '' file; do
          echo "Building $file"
          gcc "$file" -o "${file%.c}"
        done
